"""s2s-rpi-setup: prepares a Raspberry Pi for the speech-to-speech pipeline.

Run after `uv sync --extra rpi`. Tasks:
  1. Create the model directory tree under `<repo>/models/`.
  2. Write `models/.env` with HF_HOME and related variables pointing into it.
     If the file already exists with identical content, no-op; if it differs,
     the user is told to re-run with --force-env.
  3. With `--fetch`, download the recommended model weights via `hf`/`huggingface-cli`
     AND import the LiteRT-LM model via `litert-lm import`.

Everything is offline-friendly: nothing is downloaded unless `--fetch` is passed,
and the defaults never touch `~/.cache/huggingface`.
"""

from __future__ import annotations

import argparse
import hashlib
import shutil
import subprocess
import sys
from pathlib import Path
from textwrap import dedent

REPO_ROOT = Path(__file__).resolve().parents[2]
MODELS_DIR = REPO_ROOT / "models"
ENV_FILE = MODELS_DIR / ".env"

DEFAULT_MODEL_TREE = {
    "huggingface": "Hugging Face cache (transformers, datasets)",
    "moonshine": "Moonshine STT weights (UsefulSensors/moonshine-{base,streaming-medium})",
    "supertonic": "Supertonic 3 TTS cache (Supertone/supertonic-3)",
    "litert-lm": "LiteRT-LM Gemma 4 cache (.litertlm files go under HF_HOME)",
    "cactus": "Cactus Compute Gemma 4 weights",
    "run": "PID files for the launcher script",
    "log": "Log files for the launcher script",
}


# LiteRT-LM model registry. `litert-lm import` needs three things: the HF repo
# id (where the upstream .litertlm lives), a local filename to write, and an
# alias used by `litert-lm serve` to address the model.
# Source: https://huggingface.co/litert-community
LITERT_LM_MODELS: dict[str, dict[str, str]] = {
    "e4b": {
        "hf_repo": "litert-community/gemma-4-E4B-it-litert-lm",
        # Filenames on HF use capital E4B. Verified via
        # GET https://huggingface.co/api/models/litert-community/gemma-4-E4B-it-litert-lm
        "litertlm_filename": "gemma-4-E4B-it.litertlm",
        "alias": "gemma4-e4b",
        "description": "Gemma 4 E4B (4B effective params, ~2.5 GB)",
        "litertlm_path": "/home/rpi-ai/.litert-lm/models/gemma4-e4b/model.litertlm",
    },
    "e2b": {
        "hf_repo": "litert-community/gemma-4-E2B-it-litert-lm",
        "litertlm_filename": "gemma-4-E2B-it.litertlm",
        "alias": "gemma4-e2b",
        "description": "Gemma 4 E2B (2B effective params, ~1.5 GB)",
        "litertlm_path": "/home/rpi-ai/.litert-lm/models/gemma4-e2b/model.litertlm",
    },
}


def ensure_models_tree() -> None:
    """Create every subdirectory in models/. Idempotent."""
    for name in DEFAULT_MODEL_TREE:
        (MODELS_DIR / name).mkdir(parents=True, exist_ok=True)


def render_env(
    *,
    llm_backend: str,
    litert_lm_model_key: str | None,
    cactus_model_path: Path | None,
    moonshine_default: str,
    supertonic_default_voice: str,
    moonshine_stt_port: int,
    supertonic_tts_port: int,
    litert_lm_port: int,
) -> str:
    """Build the .env content. Comments explain each variable."""
    if litert_lm_model_key:
        info = LITERT_LM_MODELS[litert_lm_model_key]
        litert_block = (
            f"LITERT_LM_MODEL_ALIAS={info['alias']}\n"
            f"LITERT_LM_MODEL_PATH={info['litertlm_path']}\n"
            f"LITERT_LM_PORT={litert_lm_port}\n"
            f"LITERT_LM_BASE_URL=http://127.0.0.1:{litert_lm_port}/v1\n"
        )
    else:
        litert_block = (
            "# LITERT_LM_MODEL_ALIAS not set; install via `uv sync --extra rpi-litertlm` "
            "and rerun with --llm-backend litert-lm\n"
        )

    if cactus_model_path:
        cactus_block = (
            f"CACTUS_MODEL_PATH={cactus_model_path}\n"
            f"CACTUS_BASE_URL=http://127.0.0.1:{litert_lm_port}/v1\n"
        )
    else:
        cactus_block = (
            "# CACTUS_MODEL_PATH not set; install via `uv sync --extra rpi-cactus` "
            "and rerun with --llm-backend cactus\n"
        )

    return dedent(
        f"""\
        # Generated by s2s-rpi-setup. `source` this file before starting the pipeline.
        # Example:  set -a; source models/.env; set +a

        # --- Hugging Face cache (transformers, datasets) ---
        HF_HOME={MODELS_DIR / 'huggingface'}
        HUGGINGFACE_HUB_CACHE={MODELS_DIR / 'huggingface' / 'hub'}
        TRANSFORMERS_CACHE={MODELS_DIR / 'huggingface'}
        HF_HUB_DISABLE_PROGRESS_BARS=1

        # --- Moonshine STT ---
        MOONSHINE_MODEL_DIR={MODELS_DIR / 'moonshine'}
        MOONSHINE_DEFAULT_MODEL={moonshine_default}
        MOONSHINE_STT_PORT={moonshine_stt_port}
        MOONSHINE_STT_BASE_URL=http://127.0.0.1:{moonshine_stt_port}/v1

        # --- Supertonic 3 TTS ---
        SUPERTONIC_MODEL_DIR={MODELS_DIR / 'supertonic'}
        SUPERTONIC_DEFAULT_VOICE={supertonic_default_voice}
        SUPERTONIC_TTS_PORT={supertonic_tts_port}
        SUPERTONIC_TTS_BASE_URL=http://127.0.0.1:{supertonic_tts_port}/v1

        # --- LLM runtime (chosen via --llm-backend) ---
        S2S_LLM_BACKEND={llm_backend}
        {litert_block}{cactus_block}
        # --- Pipeline defaults for `speech-to-speech` CLI ---
        S2S_WS_HOST=0.0.0.0
        S2S_WS_PORT=8765
        """
    )


def _sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def write_env(content: str, *, overwrite: bool) -> None:
    """Write models/.env, but never silently overwrite if the content matches.

    - File missing                 -> write.
    - File present, content matches -> say "up-to-date" and no-op.
    - File present, content differs -> say so and require --force-env.
    """
    ENV_FILE.parent.mkdir(parents=True, exist_ok=True)

    if not ENV_FILE.exists():
        ENV_FILE.write_text(content)
        print(f"[ok] wrote {ENV_FILE}")
        return

    existing = ENV_FILE.read_text()
    if existing == content:
        print(f"[ok] {ENV_FILE} already up-to-date")
        return

    if overwrite:
        ENV_FILE.write_text(content)
        print(f"[ok] rewrote {ENV_FILE}")
        return

    print(f"[diff] {ENV_FILE} exists with different content. Pass --force-env to overwrite.")
    print(f"       (existing sha256: {_sha(ENV_FILE)[:12]}…, new: {hashlib.sha256(content.encode()).hexdigest()[:12]}…)")


def hf_cli_available() -> bool:
    return shutil.which("hf") is not None or shutil.which("huggingface-cli") is not None


def fetch_with_hf(repo_id: str, local_dir: Path) -> None:
    cmd = None
    if shutil.which("hf"):
        cmd = ["hf", "download", repo_id, "--local-dir", str(local_dir)]
    elif shutil.which("huggingface-cli"):
        cmd = ["huggingface-cli", "download", repo_id, "--local-dir", str(local_dir)]
    if cmd is None:
        print(f"[warn] neither `hf` nor `huggingface-cli` found; skip fetch of {repo_id}")
        return
    print(f"[fetch] {' '.join(cmd)}")
    subprocess.run(cmd, check=False, cwd=REPO_ROOT)


def litert_lm_cli_available() -> bool:
    return shutil.which("litert-lm") is not None


def hf_repo_files(repo_id: str) -> list[str]:
    """List files in a Hugging Face repo via the public API. Returns [] on error."""
    try:
        import json
        import urllib.request

        url = f"https://huggingface.co/api/models/{repo_id}"
        with urllib.request.urlopen(url, timeout=15) as resp:
            data = json.loads(resp.read())
        return [s.get("rfilename", "") for s in data.get("siblings", []) if s.get("rfilename")]
    except Exception as exc:  # noqa: BLE001
        print(f"[warn] could not list files in {repo_id}: {exc}")
        return []


def _pick_litertlm_filename(repo_id: str, preferred: str) -> str | None:
    """Pick the actual filename to download from a LiteRT-LM repo.

    Prefers `preferred` (the version-pinned one in LITERT_LM_MODELS). If it
    is missing in the repo, falls back to the first `*.litertlm` file, or
    `None` if nothing matches.
    """
    files = hf_repo_files(repo_id)
    if not files:
        return None
    if preferred in files:
        return preferred
    # Fallback: prefer the bare model variant (no hardware suffix), then any.
    bare = [f for f in files if f.endswith(".litertlm") and "_" not in Path(f).stem]
    if bare:
        return sorted(bare)[0]
    any_lm = [f for f in files if f.endswith(".litertlm")]
    return any_lm[0] if any_lm else None


def litert_lm_import(model_key: str) -> bool:
    """Import a model into LiteRT-LM's registry via `litert-lm import`.

    Returns True on success or if the alias is already registered.
    """
    if not litert_lm_cli_available():
        print("[warn] `litert-lm` not on PATH; skipping import. Install via `uv sync --extra rpi-litertlm`.")
        return False

    info = LITERT_LM_MODELS[model_key]
    alias = info["alias"]

    # Skip if already imported. litert-lm places registry files under
    # ~/.cache/litert-lm/models/<alias>/; if that directory exists, we treat
    # the import as already done.
    registry = Path.home() / ".cache" / "litert-lm" / "models" / alias
    if registry.exists():
        print(f"[skip] litert-lm already has alias '{alias}' at {registry}")
        return True

    filename = _pick_litertlm_filename(info["hf_repo"], info["litertlm_filename"])
    if filename is None:
        print(f"[fail] no .litertlm file found in {info['hf_repo']}; check the repo on Hugging Face.")
        return False
    if filename != info["litertlm_filename"]:
        print(f"[info] configured filename {info['litertlm_filename']!r} not in repo, using {filename!r} instead")

    cmd = [
        "litert-lm",
        "import",
        f"--from-huggingface-repo={info['hf_repo']}",
        filename,
        alias,
    ]
    print(f"[import] {' '.join(cmd)}")
    try:
        rc = subprocess.run(cmd, check=False, timeout=900).returncode
    except subprocess.TimeoutExpired:
        print("[fail] litert-lm import timed out after 900s")
        return False
    if rc != 0:
        print(f"[fail] litert-lm import exited with code {rc}")
        return False
    print(f"[ok] imported {info['hf_repo']} as alias '{alias}'")
    return True


def run_uv_sync(extras: list[str]) -> None:
    cmd = ["uv", "sync", "--python", sys.executable]
    for extra in extras:
        cmd.extend(["--extra", extra])
    print(f"[sync] {' '.join(cmd)}")
    subprocess.run(cmd, check=False, cwd=REPO_ROOT)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        prog="s2s-rpi-setup",
        description="Prepare a Raspberry Pi workspace for the speech-to-speech pipeline.",
    )
    p.add_argument(
        "--llm-backend",
        choices=("litert-lm", "cactus"),
        default="litert-lm",
        help="Which LLM runtime to configure defaults for.",
    )
    p.add_argument(
        "--litert-lm-model",
        choices=tuple(LITERT_LM_MODELS.keys()),
        # Default flipped to e2b on 2026-07-17: smaller, faster, ~1.5 GB.
        # Switch with `--litert-lm-model e4b` for higher quality.
        default="e2b",
        help="Which LiteRT-LM Gemma 4 variant to use (default: e2b).",
    )
    p.add_argument(
        "--moonshine-model",
        default="UsefulSensors/moonshine-base",
        help="HF repo id for the Moonshine checkpoint (default: UsefulSensors/moonshine-base).",
    )
    p.add_argument(
        "--supertonic-voice",
        default="M1",
        help="Default Supertonic voice id (M1..M5 / F1..F5). Default: M1.",
    )
    p.add_argument("--moonshine-stt-port", type=int, default=9001)
    p.add_argument("--supertonic-tts-port", type=int, default=9002)
    p.add_argument("--litert-lm-port", type=int, default=9379, help="LiteRT-LM OpenAI-compat server port (default: 9379).")
    p.add_argument(
        "--fetch",
        action="store_true",
        help="Download the recommended model weights (HF + litert-lm import).",
    )
    p.add_argument(
        "--sync",
        action="store_true",
        help="Run `uv sync` with the chosen extras before writing env.",
    )
    p.add_argument(
        "--extra",
        action="append",
        default=[],
        help="Extra to pass to `uv sync`. Repeatable. Defaults to ['rpi'].",
    )
    p.add_argument(
        "--force-env",
        action="store_true",
        help="Overwrite models/.env if it already exists with different content.",
    )
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)

    print(f"[info] repo root: {REPO_ROOT}")
    ensure_models_tree()
    print(f"[ok] models tree at {MODELS_DIR}")

    if args.sync:
        extras = args.extra or ["rpi"]
        run_uv_sync(extras)

    litert_key = args.litert_lm_model if args.llm_backend == "litert-lm" else None
    cactus_path = (MODELS_DIR / "cactus" / "gemma-4-e4b") if args.llm_backend == "cactus" else None

    env_content = render_env(
        llm_backend=args.llm_backend,
        litert_lm_model_key=litert_key,
        cactus_model_path=cactus_path,
        moonshine_default=args.moonshine_model,
        supertonic_default_voice=args.supertonic_voice,
        moonshine_stt_port=args.moonshine_stt_port,
        supertonic_tts_port=args.supertonic_tts_port,
        litert_lm_port=args.litert_lm_port,
    )
    write_env(env_content, overwrite=args.force_env)

    if args.fetch:
        # 1. Moonshine STT — Transformers downloads from HF on first load.
        if hf_cli_available():
            fetch_with_hf(args.moonshine_model, MODELS_DIR / "moonshine" / args.moonshine_model.split("/")[-1])
        else:
            print("[warn] install `huggingface_hub` to use --fetch for HF weights.")

        # 2. Supertonic TTS — same story; the package downloads on first TTS().
        # We just touch HF_HOME so it lands in the repo.
        if hf_cli_available():
            fetch_with_hf("Supertone/supertonic-3", MODELS_DIR / "supertonic")
        else:
            print("[warn] install `huggingface_hub` to pre-fetch supertonic weights.")

        # 3. LLM — the LiteRT-LM path requires `litert-lm import`; the cactus
        # path is just an HF download.
        if args.llm_backend == "litert-lm":
            litert_lm_import(args.litert_lm_model)
        else:
            if hf_cli_available():
                fetch_with_hf("google/gemma-4-E4B-it", cactus_path)
            else:
                print("[warn] install `huggingface_hub` to pre-fetch cactus weights.")

    print()
    print("Next steps:")
    print(f"  source {ENV_FILE}")
    print("  ./scripts/rpi_start.sh                # foreground")
    print("  ./scripts/rpi_start.sh --bg           # daemonized, PIDs in models/run/")
    print()
    print("If a script complains 'speech-to-speech: not found', the launcher")
    print("could not auto-detect the venv. Either:")
    print(f"  source {REPO_ROOT}/.venv/bin/activate")
    print("    # …or…")
    print("  export PATH=\"$PWD/.venv/bin:$PATH\"")
    print()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
